### ISSUE TITLE
Remove approximateSize test

### ISSUE THREAD

**Issue by vweevers** [Level/deferred-leveldown#33]
Because it was removed from abstract-leveldown.

**Comment by vweevers** [comment]
Hmm, but are we OK with not having `approximateSize` on `deferred-leveldown`? As it wraps other stores. You'd have to reach down to `db.db.db`.

@juliangruber @ralphtheninja?

**Comment by vweevers** [comment]
Maybe we can make a generic solution for custom methods?

```js
function DeferredLevelDOWN (db) {
  AbstractLevelDOWN.call(this, '')
  this._db = db
  this._operations = []
  this._iterators = []

  this.additionalDeferrables = Object.keys(db).filter(function (m) {
    return typeof db[m] === 'function'
      && AbstractLevelDOWN.prototype[m] == null
      && DeferredLevelDOWN.prototype[m] == null
  })
}

function open (obj) {
  deferrables.concat('iterator').forEach(function (m) {
    obj['_' + m] = function () {
      return this._db[m].apply(this._db, arguments)
    }
  })

  obj.additionalDeferrables.forEach(function (m) {
    obj[m] = function () {
      return this._db[m].apply(this._db, arguments)
    }
  })
}

// same for closed()
```

**Comment by ralphtheninja** [comment]
Sounds good to me.

@juliangruber WDYT?

**Comment by juliangruber** [comment]
If we use inheritance, all methods should be exposed automatically, right?

**Comment by vweevers** [comment]
@juliangruber can you please elaborate?

**Comment by juliangruber** [comment]
Sure!

```js
class Backend {
  approximateSize() { return 42 }
}

class Deferred extends Backend {}
class DB extends Deferred {}

const db = new DB()
console.log(db.approximateSize())
```

**Comment by juliangruber** [comment]
This btw is the same as:

```js
function Backend () {}
Backend.prototype.approximateSize = function () {
  return 42
}

function Deferred () {
  Backend.call(this)
}
Deferred.prototype = Object.create(Backend.prototype)

function DB () {
  Deferred.call(this)
}
DB.prototype = Object.create(Deferred.prototype)

const db = new DB()
console.log(db.approximateSize())
```

**Comment by vweevers** [comment]
This doesn't "defer" the methods until the store is opened. I mean, `deferred-leveldown` changes behavior at runtime. That's why it's a decorator rather than a subclass.

**Comment by juliangruber** [comment]
Ah, I see. Then I think ideally the other deferrables are a configuration option, instead of checking each method, right?

**Comment by vweevers** [comment]
It crossed my mind but got worried about having to explain this to people. Esp. in `level(up)`, where you'd have to pass an option to `levelup` to make `deferred-leveldown` support additional methods on the `db` that you passed to `levelup`. And sometimes you don't know what that `db` is.

Maybe instead of (user) configuration we can give stores a manifest similar to multilevel? Probably overkill though, for this particular problem.

**Comment by juliangruber** [comment]
If you're using a `level-packager` module like `level` - which most people afaik do - this would be preconfigured already.

I see the problem about using `levelup` though, where you'd need to pass down configuration. I think exposing something like multilevel's `db.manifest` indeed would be a great solution.

My vote is either to drop those extra methods completely (so people do `db.db.db....`), or add a proper solution through something like a manifest.

**Comment by vweevers** [comment]
> If you're using a level-packager module like level - which most people afaik do - this would be preconfigured already.

Ah yes, that's true.

> My vote is either to drop those extra methods completely (so people do db.db.db....), or add a proper solution through something like a manifest.

Can we do the proper solution later, and an ad-hoc solution now (like checking all methods, or maybe just `approximateSize`)? So that we can release all the new downs.

**Comment by ralphtheninja** [comment]
> Can we do the proper solution later, and an ad-hoc solution now (like checking all methods, or maybe just approximateSize)? So that we can release all the new downs.

We should be able to do that. We already have similar code in e.g. `level-packager` where we check for e.g. `destroy` and `repair` (https://github.com/Level/packager/blob/master/level-packager.js#L16). So maybe now we should just check if the `db` passed into `deferred-leveldown` has a `approximateSize` method and if so we add it to the already deferred methods.

**Comment by ralphtheninja** [comment]
I'm taking a look at this to see if I can come up with something

**Comment by vweevers** [comment]
@ralphtheninja can you open an issue for the proper solution?

**Comment by ralphtheninja** [comment]
@vweevers https://github.com/Level/deferred-leveldown/pull/32 was my solution for it

**Comment by vweevers** [comment]
I meant the manifest-like solution. The `approximateSize` solution of #32 is temporary, no?

**Comment by ralphtheninja** [comment]
Oh, right, sorry. Yes we need an issue for this. But I would much rather want you to create it 😄

**Comment by vweevers** [comment]
Alright ;)
