### ISSUE TITLE
Support seeking

### ISSUE THREAD

**Issue by vweevers** [Level/deferred-leveldown#67]
@MeirionHughes While you're on a roll, feel like taking this on as well? :)

**Comment by MeirionHughes** [comment]
ahh... this is actually the source of an issue I was having with subleveldown this afternoon. will need some special handling of seek because otherwise you get the error: 
```
TypeError: this.db._serializeKey is not a function
    at DeferredIterator.AbstractIterator.seek (D:\Code\deferred-leveldown\node_modules\abstract-leveldown\abstract-iterator.js:49:20)
```
